### ISSUE TITLE
Make iframeResizer.contentWindow.min.js available for contained pages to reference

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.iframeblock#28]
In order for this product to work `iframeResizer.contentWindow.min.js` must be included in the 'child page' (the page within the iframe), this implies using the same version as the parent page.

The best way for the 'contained site' to get a matching version of iframeResizer is to source it from the site using this product, however at the moment iframeResizer.contentWindow.min.js gets bundled in production which means it is useless for "contained sites" to reference.

We need it in the bundle in case the site references itself inside an iframe, BUT ...
can we also supply this file separately for this purpose?

This will need different solutions on Plone 4 and Plone 5.

If we do this it also needs documenting in README

**Comment by Nachtalb** [comment]
So basically your idea is that we do something like?

```html
<html>
<body data-content-window-js-url="https://bla.../contentWindow.js">
...
</body>
</html>
```

```js
if (window.parent !== window) {
	var contentWindowURL = $(window.parent.document).find('body').data('conentWindowJsUrl')
    if (contentWindowURL === undefined) {
        contentWindowURL = $('body').data('conentWindowJsUrl')
    }
	$.getScript(contentWindowURL)
}
```

**Comment by djowett-ftw** [comment]
I don't think so. I meant just a <script> tag in the other website that references the Plone website

**Comment by maethu** [comment]
So far the "other" websites are integrating the contentWindow script theme-selves. Major versions are usually compatible. At time of writing it's 4.x. 

We serve the script as well (if needed):  /++resource++ftw.iframeblock/iframeResizer.contentWindow.min.js
